default['selfsigned_certificate']['destination'] = "/usr/var/ssl/certs/"
default['selfsigned_certificate']['passphrase'] = "changeme"
default['selfsigned_certificate']['country'] = "CO"
default['selfsigned_certificate']['state'] = "ST"
default['selfsigned_certificate']['city'] = "CI"
default['selfsigned_certificate']['org'] = "OR"
default['selfsigned_certificate']['depart'] = "DE"
default['selfsigned_certificate']['cn'] = "CN"
default['selfsigned_certificate']['email'] = "EMAIL"
~
